on:
  push:
    branches: [ 'main', 'release-**' ]
  pull_request:
    branches: [ 'main', 'release-**' ]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-wasi
          components: rustfmt,rust-src,clippy
          default: true
          profile: minimal
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: run fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run tslint check
        run: yarn lint:ts:tslint
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}